#!/usr/bin/env bash

set -e

SIM=${1:-knottykraken}
BUILD_TYPE=${2:-release}
CUSTOM_GCC=${3:-system}

FLEXUS_ROOT=$(realpath flexus)
QEMU_ROOT=$(realpath qemu)

profile="-pr ${FLEXUS_ROOT}/target/_profile/${BUILD_TYPE}"

if [ "$CUSTOM_GCC" = "custom" ]; then
    profile="${profile} -pr ${FLEXUS_ROOT}/target/_profile/custom-gcc"
fi

case $SIM in
    *kraken)
        conan build $FLEXUS_ROOT $profile --name=$SIM -of out -b missing
        conan export-pkg $FLEXUS_ROOT $profile --name=$SIM -of out
        ;;
    docker)
        docker buildx build -t parsa/qflex-${BUILD_TYPE}:latest --build-arg MODE=${BUILD_TYPE} .
        ;;
    [cC][Qq]|qemu)
        pushd $QEMU_ROOT

        if [ "$BUILD_TYPE" = "debug" ]; then
            ./configure --target-list=aarch64-softmmu       \
                        --disable-docs                      \
                        --enable-capstone                   \
                        --enable-slirp                      \
                        --enable-libqflex                   \
                        --enable-snapvm-external            \
                        --enable-debug                      \
                        --extra-cflags="-fsanitize=address" \
                        --extra-cflags="-fno-omit-frame-pointer"

        else
            ./configure --target-list=aarch64-softmmu       \
                        --disable-docs                      \
                        --enable-capstone                   \
                        --enable-slirp                      \
                        --enable-snapvm-external            \
                        --enable-libqflex

        fi
        popd
        make -C qemu -j
        ;;
    [Qq])
        make -C qemu -j
        ;;
    *)
        echo "Never heard of '${SIM}'"
        exit 1
        ;;
esac
