#!/usr/bin/env bash

set -xev

SIM=${1:-KeenKraken}
DEV=${2:-yes}

FLEXUS_ROOT=$(realpath flexus)
QEMU_ROOT=$(realpath qemu)
case $SIM in
    *Kraken)
        cmake ${FLEXUS_ROOT}                        \
            -B ${SIM}                               \
            -DCMAKE_C_COMPILER=$(which gcc)      \
            -DCMAKE_CXX_COMPILER=$(which g++)    \
            -DSIMULATOR=${SIM}                      \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON      \
            -DCMAKE_CXX_FLAGS="-DFLEXUS -Wno-error=dangling-pointer" \
            -DBUILD_DEBUG=${DEV}

        cmake                       \
            --build ${SIM}	        \
            -j4

        ;;



    [cC][Qq]|qemu)
        pushd $QEMU_ROOT

        if [ "$DEV" = "yes" ]; then
            ./configure --target-list=aarch64-softmmu       \
                        --disable-docs                      \
                        --enable-savevm-external            \
                        --enable-libqflex                   \
                        --enable-debug                      \
                        --extra-cflags="-fsanitize=address" \
                        --extra-cflags="-fno-omit-frame-pointer"

        else
            ./configure --target-list=aarch64-softmmu       \
                        --disable-docs                      \
                        --enable-savevm-external            \
                        --enable-libqflex

        fi
        popd
        make -C qemu -j4
        ;;
    [Qq])
        make -C qemu -j4
        ;;
    *)
        echo "Never heard of '${SIM}'"
        exit 1
        ;;
esac
