#!/usr/bin/env python

import typer
from typing import Annotated
from commands.docker import DockerStarter, DockerBuild

app = typer.Typer(
    name="./dep",
    help="A CLI tool to manage QFlex dependancies and images. (suggest running ./dep --show-completion >> ~/.bashrc && source ~/.bashrc to enable autocompletions)",
)

# TODO remove worm option once fully released and integrated
@app.command()
def build_docker(
    debug: Annotated[bool, typer.Option(help="Build the Docker image in debug mode.")] = False,
    worm: Annotated[bool, typer.Option(help="Build the Docker image with WORM support. Experimental")] = False,
    worm_only: Annotated[bool, typer.Option(help="Re-build only the WormCacheQFlex component.")] = False,
    push: Annotated[bool, typer.Option(help="Push the built image to github container registery. Requires authentication.")] = False,
):
    """
    Build the Docker image for QFlex. Use --debug to build a debug version.
    Useful for development and testing without installing dependencies locally.
    """
    docker_build_executor = DockerBuild(debug=debug, worm=worm, worm_only=worm_only, push=push)
    docker_build_executor.execute(to_stdio=True, run_in_background=False)


@app.command()
def start_docker(
    mounting_folder: Annotated[str, typer.Option(help="Folder to mount for files.")],
    debug: Annotated[bool, typer.Option(help="Start the Docker container in debug mode.")] = False, 
    worm: Annotated[bool, typer.Option(help="Build the Docker image with WORM support. Experimental")] = False,
    start_directory: Annotated[str, typer.Option(help="Directory to start in inside the container.")] = None,
):
    """
    Start a Docker container with the QFlex environment. 
    Useful for development and testing without installing dependencies locally.
    """
    docker_executor = DockerStarter(mounting_folder=mounting_folder, debug=debug, worm=worm, start_directory=start_directory)
    docker_executor.execute(to_stdio=True, run_in_background=False)
    # TODO bring in the build scripts here as well


if __name__ == "__main__":
    app()