ARG BASE_IMAGE

FROM ${BASE_IMAGE}

# Rust toolchain, cargo, and inferno are installed in the base image now.
# This file only adds WormCacheQFlex-specific bits on top.

WORKDIR /home/dev/qflex

COPY ./WormCacheQFlex /home/dev/qflex/WormCacheQFlex
# TODO temp fix because of not caching in the previous step 
COPY ./qflex /home/dev/qflex/qflex
COPY ./commands /home/dev/qflex/commands

# TODO temp fix for micro for old imports
RUN mkdir /qflex
RUN ln -s /home/dev/qflex/qemu-saved /qflex/qemu-saved 
RUN ln -s /home/dev/qflex/parallel-qemu-saved /qflex/p-qemu-saved 
COPY ./micro_scripts /home/dev/qflex/micro_scripts

CMD ["bash"]



