ARG BASE_IMAGE=parsa/qflex-release

FROM ${BASE_IMAGE}


WORKDIR /deps

RUN mkdir /home/dev/.cargo
RUN touch /home/dev/.cargo/env

RUN apt-get update && apt-get install -y curl build-essential
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN . "/home/dev/.cargo/env" 
RUN echo 'source /home/dev/.cargo/env' >> /etc/bash.bashrc


WORKDIR /home/dev/qflex

COPY ./WormCache /home/dev/qflex/WormCache 

CMD ["bash"]



