ARG BASE_IMAGE

FROM ${BASE_IMAGE}


# Rust (RUSTUP_HOME/CARGO_HOME/PATH) is provided by the base image, see Dockerfile.

WORKDIR /home/dev/qflex

COPY ./WormCache /home/dev/qflex/WormCache
# TODO temp fix because of not caching in the previous step 
COPY ./qflex /home/dev/qflex/qflex
COPY ./commands /home/dev/qflex/commands

# TODO temp fix for micro for old imports
RUN mkdir /qflex
RUN ln -s /home/dev/qflex/timing-qemu-saved /qflex/qemu-saved 
RUN ln -s /home/dev/qflex/fw-qemu-saved /qflex/p-qemu-saved 
COPY ./micro_scripts /home/dev/qflex/micro_scripts

CMD ["bash"]



