name: Build QFlex container
run-name: '[${{ github.event_name }}] ${{ github.ref_name }}'

env:
  DOCKER_BUILD_SUMMARY: true
  DOCKER_BUILD_RECORD_UPLOAD: false

on:
  push:
    branches:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build_container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      #matrix:
      #  binaries:
      #    - release
      #    - debug
    steps:
      - name: Clone QFlex
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: parsa/qflex:latest


