name: web-pages-build

on:
  push:
    branches: [ "gitflow-clean-up-cyan-qflex-exp" ]
  pull_request:
    branches: [ "gitflow-clean-up-cyan-qflex-exp" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.docs.txt
          
      - name: Build static site into /docs
        run: |
          make build-docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site"

  deploy:
    # Add condition to only deploy on push (not PR)
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Updated to v4